controllers/SiteController.php
<?php
/**
 * Created by PhpStorm.
 * User: Saburov Denis
 * Date: 26.03.18
 */

namespace app\controllers;

use app\helpers\ReferralHelper;
use app\models\AbstractModel;
use app\models\form\LoginForm;
use app\models\form\UserForm;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\ErrorAction;
use yii\web\Response;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only'  => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow'   => true,
                        'roles'   => ['@'],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => ErrorAction::class,
            ],
        ];
    }

    /**
     * Главная страница
     *
     * @return Response|string
     * @throws \yii\base\InvalidArgumentException
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Страница входа
     *
     * @return Response|string
     * @throws \yii\base\InvalidArgumentException
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $loginForm = new LoginForm();
        if ($loginForm->load(Yii::$app->request->post()) && $loginForm->login()) {
            return $this->goBack();
        }

        $loginForm->password = '';

        return $this->render('login', [
            'model' => $loginForm,
        ]);
    }

    /**
     * Страница сохранения реферера (пригласившего)
     *
     * @param int $id
     *
     * @return Response|string
     */
    public function actionReferral(int $id)
    {
        if (Yii::$app->user->isGuest) {
            ReferralHelper::setReferrerId($id);
        }

        return $this->redirect('site/registration');
    }

    /**
     * Страница регистрации
     *
     * @return Response|string
     * @throws \yii\base\InvalidArgumentException
     * @throws \yii\db\Exception
     */
    public function actionRegistration()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $userForm = new UserForm();
        if ($userForm->load(Yii::$app->request->post())) {

            $referrerId = ReferralHelper::getReferrerId();
            $referrer = $referrerId !== null ? $this->getUser((int)$referrerId) : null;
            $userForm->setReferrer($referrer);

            if ($userForm->save() && $userForm->login()) {
                $message = 'Спасибо за регистрацию.';
                if ($referrer !== null) {
                    $message .= ' Вас пригласил ' . $referrer;
                }
                Yii::$app->session->setFlash('success', $message);
                ReferralHelper::removeReferrer();

                return $this->goHome();
            }
            $this->addErrorForForm($userForm);
        }
        $userForm->password = '';

        return $this->render('registration', [
            'model' => $userForm,
        ]);
    }

    /**
     * Страница выхода
     *
     * @return Response|string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Страница профиля
     *
     * @return Response|string
     *
     * @throws \yii\base\InvalidArgumentException
     */
    public function actionProfile()
    {
        try {
            /** @var User $user */
            $user = Yii::$app->user->getIdentity();
            if ($user !== null) {
                return $this->render('profile', [
                    'user'      => $user,
                    'referrals' => $user->getReferrals(),
                    'referrer'  => $user->getReferrer(),
                ]);
            }

        } catch (\Exception $e) {
            Yii::error($e->getMessage(), 'profile');
        } catch (\Throwable $e) {
            Yii::error($e->getMessage(), 'profile');
        }

        return $this->goHome();
    }

    /**
     * @param AbstractModel $form
     */
    private function addErrorForForm(AbstractModel $form): void
    {
        $message = $form->hasErrors()
            ? $form->getModelErrors()
            : 'При регистрации произошла ошибка, мы уже работаем над ней. Для решения проблемы напишите нам ' . Yii::$app->params['supportEmail'];
        Yii::$app->session->setFlash('error', $message);
    }

    /**
     * @param $id
     *
     * @return User|null
     */
    private function getUser(int $id): ?User
    {
        return User::find()->getById($id);
    }
}

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'My Yii Application';
?>
<div class="site-index">

	<div class="jumbotron">
		<h1>Добро пожаловать!</h1>

		<p class="lead">Партнерская система.</p>

		<p>
            <?= Html::a('Зарегистрироваться', ['site/registration'], ['class' => 'btn btn-lg btn-success']) ?>
		</p>
	</div>

	<div class="body-content">

		<div class="row">
			<div class="col-lg-4">
				<h2>Выгодно</h2>

				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
				   et
				   dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
				   aliquip
				   ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore
				   eu
				   fugiat nulla pariatur.</p>

				<p>
                    <?= Html::a('Регистрация', ['site/registration'], ['class' => 'btn btn-default']) ?>
				</p>
			</div>
			<div class="col-lg-4">
				<h2>Интересно</h2>

				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
				   et
				   dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
				   aliquip
				   ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore
				   eu
				   fugiat nulla pariatur.</p>

				<p>
                    <?= Html::a('Регистрация', ['site/registration'], ['class' => 'btn btn-default']) ?>
				</p>
			</div>
			<div class="col-lg-4">
				<h2>Прибыльно</h2>

				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
				   et
				   dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
				   aliquip
				   ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore
				   eu
				   fugiat nulla pariatur.</p>

				<p>
                    <?= Html::a('Регистрация', ['site/registration'], ['class' => 'btn btn-default']) ?>
				</p>
			</div>
		</div>

	</div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\form\LoginForm */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = 'Вход';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
	<h1><?= Html::encode($this->title) ?></h1>

	<p>Пожалуйста, заполните следующие поля для входа:</p>

    <?php $form = ActiveForm::begin([
        'id'          => 'login-form',
        'layout'      => 'horizontal',
        'fieldConfig' => [
            'template'     => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'rememberMe')->checkbox([
        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
    ]) ?>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
		</div>
	</div>

    <?php ActiveForm::end(); ?>
</div>

views/site/profile.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $user app\models\User */
/* @var $referrals app\models\User[] */

/* @var $referrer app\models\User */

use app\models\User;
use yii\helpers\Html;

$this->title = 'Профиль пользователя';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
	<h1><?= Html::encode($this->title) ?></h1>

	<div class="jumbotron">
		<h1>Партнерская система</h1>

		<p class="lead">Уникальная возможность пригласить в нашу партнерскую систему любого желающего</p>

		<p>
			Ваша партнерская ссылка:
			<span class="label label-success">
				<?= Yii::$app->getUrlManager()->createAbsoluteUrl(['site/referral', 'id' => $user->id]) ?>
			</span>
		</p>
	</div>

	<div class="col-md-6">
        <?= $user->getPlaceholder(User::COL_USERNAME) ?>:
		<span class="text-muted"><?= $user->username ?></span> <br>

        <?= $user->getPlaceholder(User::COL_EMAIL) ?>:
		<span class="text-muted"><?= $user->email ?></span> <br>

        <?= $user->getPlaceholder(User::COL_DATE_CREATE) ?>:
		<span class="text-muted"><?= Yii::$app->getFormatter()->asDatetime($user->created_at) ?></span> <br>
	</div>

	<div class="col-md-6">
        <?php if ($referrer !== null): ?>
			<div class="col-md-12">
				Вы пришли от: <span class="text-info"><?= $referrer ?></span>
			</div>
        <?php endif; ?>
		<div class="col-md-12" style="padding-top: 10px">
            <?php if (!empty($referrals)): ?>
				От вас пришли:
				<ol>
                    <?php foreach ($referrals as $referral): ?>
						<li><span class="text-success"><?= $referral ?></span></li>
                    <?php endforeach; ?>
				</ol>
            <?php else: ?>
				Вы еще никого не пригласили :-(
            <?php endif; ?>
		</div>
	</div>
</div>

views/site/registration.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model app\models\form\LoginForm */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
	<h1><?= Html::encode($this->title) ?></h1>

	<p>Пожалуйста, заполните следующие поля для регистрации:</p>

    <?php $form = ActiveForm::begin([
        'id'          => 'login-form',
        'layout'      => 'horizontal',
        'fieldConfig' => [
            'template'     => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>
    <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Зарегистрироваться', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
		</div>
	</div>

    <?php ActiveForm::end(); ?>

	<div class="col-lg-offset-1" style="color:#999;">
		После регистрация у Вас будет своя <strong>реферальная ссылка</strong>.<br>
	</div>
</div>